[features]
seeds = false
[programs.localnet]
the_dao_vault = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha tests/**/*.ts"
