[env]
RESTAKING_PROGRAM_ID = "GGZVdfqbuT2MpAVcaen3npXhtJ2Tgk8TwEnvXJcqer7a"
VAULT_PROGRAM_ID = "GzKVJyvn8dmHqU9pEgoYRGrRVBptyBS6UqyTi1LzBPS7"
RESOLVER_PROGRAM_ID = "AE7fSUJSGxMzjNxSPpNTemrz9cr26RFue4GwoJ1cuR6f"
