[package]
name = "resolver-sdk"
version = "0.0.1"
edition = "2021"

[dependencies]
borsh = { workspace = true }
jito-vault-program = { workspace = true }
solana-program = { workspace = true }
spl-token = { workspace = true }
thiserror = { workspace = true }
